label_tags = function(capitalize = "none", wrap = Inf) {
  scales:::force_all(capitalize, wrap)
  function(x) {
    tag_labels <- data.frame(
      label = c(
        "à la carte model",
        "à la carte model",
        "accommodations provided to all students",
        "accommodations provided to all students",
        "adaptive content",
        "adaptive content",
        "advancement on mastery",
        "advancement on mastery",
        "student advisories",
        "student advisories",
        "flexible assessment schedule",
        "flexible assessment schedule",
        "blended learning",
        "blended learning",
        "career prep and work-based learning",
        "career prep and work-based learning",
        "dialogue circles",
        "dialogue circles",
        "community and business partnerships",
        "community and business partnerships",
        "family and community support services",
        "family and community support services",
        "family and community support services",
        "competency/mastery-based education",
        "competency/mastery-based education",
        "competency framework",
        "competency framework",
        "culturally responsive practices",
        "culturally responsive practices",
        "data analytics drive instruction",
        "data analytics drive instruction",
        "design at the margins",
        "design at the margins",
        "design thinking process",
        "design thinking process",
        "take home devices",
        "take home devices",
        "no tracked classes",
        "no tracked classes",
        "no tracked classes",
        "supports for English Language Learners",
        "supports for English Language Learners",
        "enriched virtual model",
        "enriched virtual model",
        "design to meet needs of students who have been marginalized",
        "design to meet needs of students who have been marginalized",
        "design to meet needs of students who have been marginalized",
        "commitment to equity in strategic plan",
        "commitment to equity in strategic plan",
        "experiential, work-based & place-based learning",
        "experiential, work-based & place-based learning",
        "flex model",
        "flex model",
        "flexible facilities & classroom design",
        "flexible facilities & classroom design",
        "flexible schedule",
        "flexible schedule",
        "flexible staffing & alternative teaching roles",
        "flexible staffing & alternative teaching roles",
        "flipped classroom",
        "flipped classroom",
        "grading policies focus on mastery",
        "grading policies focus on mastery",
        "supports for students off-track for graduation",
        "supports for students off-track for graduation",
        "hiring practices in support of student success",
        "hiring practices in support of student success",
        "supports for immigrants and refugees",
        "supports for immigrants and refugees",
        "individual rotation",
        "individual rotation",
        "access to information in multiple formats",
        "access to information in multiple formats",
        "interoperable data from multiple technologies",
        "interoperable data from multiple technologies",
        "interoperable data from multiple technologies",
        "interdisciplinary",
        "interdisciplinary",
        "lab rotation",
        "lab rotation",
        "learner agency",
        "learner agency",
        "individual learner profiles",
        "individual learner profiles",
        "individual learning paths",
        "individual learning paths",
        "place-based learning",
        "place-based learning",
        "place-based learning",
        "connecting local and global",
        "connecting local and global",
        "maker/design-centered learning",
        "maker/design-centered learning",
        "makerspace",
        "makerspace",
        "assessments for career readiness",
        "assessments for career readiness",
        "assessments for career readiness",
        "measures for school climate",
        "measures for school climate",
        "measures for college readiness",
        "measures for college readiness",
        "assessments for deeper learning",
        "assessments for deeper learning",
        "assessments for deeper learning",
        "measures for purpose and agency",
        "measures for purpose and agency",
        "assessments for social-emotional skills",
        "assessments for social-emotional skills",
        "assessments for social-emotional skills",
        "mental health services",
        "mental health services",
        "1:1 mentoring",
        "1:1 mentoring",
        "multi-age classrooms",
        "multi-age classrooms",
        "alternating days",
        "alternating days",
        "alternating weeks",
        "alternating weeks",
        "anti-racist practices",
        "anti-racist practices",
        "asynchronous online learning",
        "asynchronous online learning",
        "digital materials",
        "digital materials",
        "dual credit",
        "dual credit",
        "dual language programming",
        "dual language programming",
        "early college high school",
        "early college high school",
        "families can choose instructional modality",
        "families can choose instructional modality",
        "families as co-leaders",
        "families as co-leaders",
        "families as co-leaders",
        "at-home learning supports",
        "at-home learning supports",
        "fully in-person",
        "fully in-person",
        "fully remote",
        "fully remote",
        "half days",
        "half days",
        "hiring for equity and inclusion values",
        "hiring for equity and inclusion values",
        "hybrid",
        "hybrid",
        "students earn industry credentials",
        "students earn industry credentials",
        "students meet industry professionals",
        "students meet industry professionals",
        "adult wellness/SEL",
        "all courses designed for inclusion",
        "all courses designed for inclusion",
        "assessments for agency and self-directed learning",
        "bilingual assessments",
        "co-leadership",
        "co-leadership",
        "community-based organizations as co-leaders",
        "community-based organizations as co-leaders",
        "heritage language course(s)",
        "heritage language course(s)",
        "industry-based partners as co-leaders",
        "industry-based partners as co-leaders",
        "other co-leaders",
        "translanguaging",
        "disaggregated data on student participation",
        "multi-tiered system of support (MTSS) in academics",
        "students as co-leaders",
        "students as co-leaders",
        "all virtual pathway",
        "peer to peer support",
        "peer to peer support",
        "print materials",
        "print materials",
        "remote accommodations",
        "remote accommodations",
        "rotating or staggered schedules",
        "rotating or staggered schedules",
        "social justice focus",
        "social justice focus",
        "synchronous online learning",
        "synchronous online learning",
        "teachers can choose instructional modality",
        "teachers can choose instructional modality",
        "teachers as co-leaders",
        "teachers as co-leaders",
        "teachers as co-leaders",
        "trauma-informed practices",
        "trauma-informed practices",
        "tutoring",
        "tutoring",
        "virtual enrichment activities",
        "virtual enrichment activities",
        "open educational resources",
        "open educational resources",
        "expanded open hours",
        "expanded open hours",
        "multiple opportunities to demonstrate mastery",
        "multiple opportunities to demonstrate mastery",
        "extended learning opportunities",
        "extended learning opportunities",
        "extended learning opportunities",
        "project-based learning",
        "project-based learning",
        "performance based assessment",
        "performance based assessment",
        "physical well being services",
        "physical well being services",
        "physical well being services",
        "portfolios and public exhibitions of student work",
        "portfolios and public exhibitions of student work",
        "portfolios and public exhibitions of student work",
        "portfolios and public exhibitions of student work",
        "supports for high-poverty and homeless students",
        "supports for high-poverty and homeless students",
        "projects as primary method of learning",
        "projects as primary method of learning",
        "high quality instructional materials",
        "high quality instructional materials",
        "real time data use to drive instruction",
        "real time data use to drive instruction",
        "real-world problem solving",
        "real-world problem solving",
        "reallocation of resources for those most in need",
        "reallocation of resources for those most in need",
        "expanded measures of success",
        "expanded measures of success",
        "expanded measures of success",
        "relevant and contextualized learning assignments",
        "relevant and contextualized learning assignments",
        "restorative practices",
        "restorative practices",
        "rigorous coursework for all students",
        "rigorous coursework for all students",
        "social-emotional learning",
        "social-emotional learning",
        "SEL curriculum",
        "SEL curriculum",
        "SEL integration school-wide",
        "SEL integration school-wide",
        "commitment to whole child or SEL in strategic plan",
        "commitment to whole child or SEL in strategic plan",
        "service learning",
        "service learning",
        "flexible staffing & infrastructure",
        "flexible staffing & infrastructure",
        "station rotation",
        "station rotation",
        "student-led conferences",
        "student-led conferences",
        "students access their own data",
        "students access their own data",
        "student-led goal setting",
        "student-led goal setting",
        "self-paced learning",
        "self-paced learning",
        "students develop projects",
        "students develop projects",
        "universal design for learning",
        "universal design for learning",
        "multiple ways to demonstrate mastery",
        "multiple ways to demonstrate mastery",
        "wraparound services & integrated student supports",
        "wraparound services & integrated student supports"),
      tag = c(
        "practices_a_la_carte",
        "a_la_carte",
        "practices_accommodations",
        "accommodations",
        "practices_adaptive_content",
        "adaptive_content",
        "practices_advancement_mastery",
        "advancement_mastery",
        "practices_advisories",
        "advisories",
        "practices_assessment_schedule",
        "assessment_schedule",
        "practices_blended_learning",
        "blended_learning",
        "practices_career_prep",
        "career_prep",
        "practices_circles",
        "circles",
        "practices_community_partnerships",
        "community_partnerships",
        "practices_community_supports",
        "community_supports",
        "community_support",
        "practices_competency_education",
        "competency_education",
        "practices_competency_framework",
        "competency_framework",
        "practices_culturally_responsive",
        "culturally_relevant",
        "practices_data_instruction",
        "data_instruction",
        "practices_design_margins",
        "design_margins",
        "practices_design_thinking",
        "design_thinking",
        "practices_devices_home",
        "devices_home",
        "practices_no_tracking",
        "practices_elimination_tracking",
        "elimination_tracking",
        "practices_ell_supports",
        "ell_supports",
        "practices_enriched_virtual",
        "enriched_virtual",
        "practices_design_marginalized",
        "design_equity",
        "equity",
        "practices_equity_plan",
        "equity_plan",
        "practices_experiential",
        "experiential",
        "practices_flex",
        "flex",
        "practices_flexible_facilities",
        "flexible_facilities",
        "practices_flexible_schedule",
        "flexible_schedule",
        "practices_flexible_staffing",
        "flexible_staffing",
        "practices_flipped_classroom",
        "flipped_classroom",
        "practices_grading_mastery",
        "grading_mastery",
        "practices_graduation_supports",
        "graduation_supports",
        "practices_hiring_practices",
        "hiring_practices",
        "practices_immigrants_supports",
        "immigrants_supports",
        "practices_individual_rotation",
        "individual_rotation",
        "practices_information_formats",
        "information_formats",
        "practices_interoperability",
        "interoperability",
        "integrated_data",
        "practices_interdisciplinary",
        "interdisciplinary",
        "practices_lab_rotation",
        "lab_rotation",
        "practices_learner_agency",
        "learner_agency",
        "practices_learner_profiles",
        "learner_profiles",
        "practices_learning_paths",
        "learning_paths",
        "practices_place_based",
        "place_based",
        "local_focus",
        "practices_local_global",
        "local_global",
        "practices_maker",
        "maker",
        "practices_makerspace",
        "makerspace",
        "practices_assessments_career",
        "assessments_career",
        "measures_career",
        "practices_measures_climate",
        "measures_climate",
        "practices_measures_college",
        "measures_college",
        "practices_assessments_deeper",
        "assessments_deeper",
        "measures_deeper",
        "practices_measures_purpose",
        "measures_purpose",
        "practices_assessments_sel",
        "assessments_sel",
        "measures_sel",
        "practices_mental_health",
        "mental_health",
        "practices_mentoring",
        "mentoring",
        "practices_multi_age",
        "multi_age",
        "practices_alternating_days",
        "alternating_days",
        "practices_alternating_weeks",
        "alternating_weeks",
        "practices_anti_racist",
        "anti_racist_action",
        "practices_asynchronous_online",
        "asynchronous_online",
        "practices_digital_materials",
        "digital_materials",
        "practices_dual_credit",
        "dual_credit",
        "practices_dual_language",
        "dual_language",
        "practices_early_college",
        "early_college",
        "practices_families_choose_modality",
        "families_choose_modality",
        "practices_colead_family",
        "practices_families_leaders",
        "families_leaders",
        "practices_family_learning",
        "family_learning",
        "practices_fully_in_person",
        "fully_in_person",
        "practices_fully_remote",
        "fully_remote",
        "practices_half_days",
        "half_days",
        "practices_hiring_equity",
        "hiring_equity",
        "practices_hybrid",
        "hybrid",
        "practices_industry_credentials",
        "industry_credentials",
        "practices_meet_professionals",
        "meet_professionals",
        "practices_adult_wellness",
        "practices_inclusion",
        "practices_all_courses_designed_for_inclusion",
        "practices_assessments_agency",
        "practices_assessments_bilingual",
        "practices_coleadership",
        "practices_co_leaders",
        "practices_colead_cbo",
        "practices_community_leaders",
        "practices_heritage",
        "practices_heritage_language",
        "practices_colead_industry",
        "practices_industry_leaders",
        "practices_other_leaders",
        "practices_translanguaging",
        "practices_disaggregated_participation_data",
        "practices_mtss_academics",
        "practices_colead_students",
        "practices_students_leaders",
        "practices_virtual_pathway",
        "practices_peer_to_peer",
        "peer_to_peer",
        "practices_print_materials",
        "print_materials",
        "practices_remote_accommodations",
        "remote_accommodations",
        "practices_rotating_schedule",
        "rotating_schedule",
        "practices_social_justice",
        "social_justice",
        "practices_synchronous_online",
        "synchronous_online",
        "practices_teachers_choose_modality",
        "teachers_choose_modality",
        "practices_colead_teachers",
        "practices_teachers_leaders",
        "teachers_leaders",
        "practices_trauma_informed",
        "trauma_informed",
        "practices_tutoring",
        "tutoring",
        "practices_virtual_enrichment",
        "virtual_enrichment",
        "practices_oer",
        "oer",
        "practices_expanded_open_hours",
        "open_hours",
        "practices_opportunities_mastery",
        "opportunities_mastery",
        "practices_extended_learning",
        "extended_learning",
        "outside_credit",
        "practices_pbl",
        "pbl",
        "practices_performance_assessment",
        "performance_assessment",
        "practices_physical_well_being",
        "physical_well_being",
        "physical_health",
        "practices_portfolios_exhibitions",
        "portfolios_exhibitions",
        "portfolios",
        "exhibitions",
        "practices_poverty_supports",
        "poverty_supports",
        "practices_projects_primary",
        "projects_primary",
        "practices_quality_materials",
        "quality_materials",
        "practices_real_time_data",
        "real_time_data",
        "practices_real_world",
        "real_world",
        "practices_reallocation_resources",
        "reallocation_resources",
        "practices_expanded_success",
        "expanded_success",
        "redefining_success",
        "practices_relevant_learning",
        "relevant_learning",
        "practices_restorative",
        "restorative_practice",
        "practices_rigorous_coursework",
        "rigorous_coursework",
        "practices_sel",
        "sel",
        "practices_sel_curriculum",
        "sel_curriculum",
        "practices_sel_integrated",
        "sel_integrated",
        "practices_sel_plan",
        "sel_plan",
        "practices_service_learning",
        "service_learning",
        "practices_staffing_infrastructure",
        "staffing_infrastructure",
        "practices_station_rotation",
        "station_rotation",
        "practices_student_conferences",
        "student_conferences",
        "practices_student_data",
        "student_data",
        "practices_student_goals",
        "student_goals",
        "practices_student_pace",
        "student_pace",
        "practices_student_projects",
        "student_projects",
        "practices_udl",
        "udl",
        "practices_ways_mastery",
        "ways_mastery",
        "practices_wraparound",
        "wraparound"))
    if(any(!x %in% tag_labels$tag)) warning("Missing tag label")
    labels = tag_labels$label[match(x, tag_labels$tag)]
    labels[is.na(labels)] = x[is.na(labels)]
    if(capitalize == "title") {
      labels = str_to_title(labels)
    }
    if(capitalize == "first") {
      labels = str_to_sentence(labels)
    }
    if(is.finite(wrap)) {
      labels = str_wrap(labels, width = wrap)
    }
    return(labels)
  }
}
